# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hector < Formula
  desc "Pure A2A-Native Declarative AI Agent Platform"
  homepage "https://github.com/verikod/hector"
  version "1.40.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verikod/hector/releases/download/v1.40.2/hector_1.40.2_darwin_amd64.tar.gz"
      sha256 "8e337b922f24119411ceb04bd3e749ccfab6f39a122910d19e9fdac4c3e60e8c"

      def install
        bin.install "hector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verikod/hector/releases/download/v1.40.2/hector_1.40.2_darwin_arm64.tar.gz"
      sha256 "8cc4caf82ed531de3f5a799a53ebe8a4b8f602cb7e53ff4fd3da865811382f23"

      def install
        bin.install "hector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/verikod/hector/releases/download/v1.40.2/hector_1.40.2_linux_amd64.tar.gz"
      sha256 "2bfe790fccc98832d3753d78052ef790a687f9a9194dbf8c359726d08f7ea033"
      def install
        bin.install "hector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verikod/hector/releases/download/v1.40.2/hector_1.40.2_linux_arm64.tar.gz"
      sha256 "62b19da9f73b224e805133401e8742ab7bd0b29970f1c3b7f6ccdf4acc398778"
      def install
        bin.install "hector"
      end
    end
  end

  test do
    system "#{bin}/hector version"
  end
end
