# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hector < Formula
  desc "Pure A2A-Native Declarative AI Agent Platform"
  homepage "https://github.com/verikod/hector"
  version "1.40.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verikod/hector/releases/download/v1.40.1/hector_1.40.1_darwin_amd64.tar.gz"
      sha256 "cd4292bb8663ed421d48e2b54db7f75d8c9d07bda8f2ccbd2eeeebc601aa1fb5"

      def install
        bin.install "hector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verikod/hector/releases/download/v1.40.1/hector_1.40.1_darwin_arm64.tar.gz"
      sha256 "73af8d1262ce5023efe61a043b716580c036c95dfe451a231424535dbbad3e8d"

      def install
        bin.install "hector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/verikod/hector/releases/download/v1.40.1/hector_1.40.1_linux_amd64.tar.gz"
      sha256 "23652a8cd7a9bb6009f00e63fa03440249ef7ecc0eb6c64cba56d4010c141e9a"
      def install
        bin.install "hector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verikod/hector/releases/download/v1.40.1/hector_1.40.1_linux_arm64.tar.gz"
      sha256 "7e5fcf625a6e9da9f2e644a16302d7d09ecc2535e90e356ac077be667de90f8b"
      def install
        bin.install "hector"
      end
    end
  end

  test do
    system "#{bin}/hector version"
  end
end
