# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hector < Formula
  desc "Pure A2A-Native Declarative AI Agent Platform"
  homepage "https://github.com/verikod/hector"
  version "1.31.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verikod/hector/releases/download/v1.31.4/hector_1.31.4_darwin_amd64.tar.gz"
      sha256 "94dcdb0f559512fdf4b04a57b6452313c86f0255921f7f35d5c1ed16e2bb34f0"

      def install
        bin.install "hector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verikod/hector/releases/download/v1.31.4/hector_1.31.4_darwin_arm64.tar.gz"
      sha256 "9d12e18678a7217d2d4e41c60182323511b849f820520a5c3124a2c748298ec5"

      def install
        bin.install "hector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/verikod/hector/releases/download/v1.31.4/hector_1.31.4_linux_amd64.tar.gz"
      sha256 "528c03384e26392e3ae23c9789ee5bdd692520d9ca85cea74eea0ca36e18d330"
      def install
        bin.install "hector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verikod/hector/releases/download/v1.31.4/hector_1.31.4_linux_arm64.tar.gz"
      sha256 "baaf0651a08635208b2c9c89cc6e9d909028c6f5cbe131e5fbf15fc0ed721855"
      def install
        bin.install "hector"
      end
    end
  end

  test do
    system "#{bin}/hector version"
  end
end
